export default function Terms() {
  return (
    <main className="flex-1 flex flex-col items-center px-4 py-12 max-w-2xl mx-auto font-[family-name:var(--font-pixel-body)]">
      <h1 className="font-[family-name:var(--font-pixel)] text-lg text-accent mb-8">TERMS OF USE</h1>

      <div className="flex flex-col gap-6 text-sm text-muted leading-relaxed">
        <p className="text-foreground text-xs">Last updated: April 6, 2026</p>

        <section>
          <h2 className="text-foreground font-bold mb-2">What this is</h2>
          <p>Screenshot Court is an entertainment tool. Verdicts, roasts, charges, and sentences are AI-generated humor — not legal advice, professional counseling, or actual court rulings. Don&apos;t take them seriously.</p>
        </section>

        <section>
          <h2 className="text-foreground font-bold mb-2">Your responsibility</h2>
          <ul className="list-disc pl-5 flex flex-col gap-1">
            <li>You must have the right to share any screenshots you upload. Don&apos;t upload conversations you don&apos;t have permission to share.</li>
            <li>Don&apos;t upload content containing minors, illegal activity, or sensitive personal information (bank details, passwords, medical records, etc.).</li>
            <li>You are responsible for how you use and share the results.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-foreground font-bold mb-2">AI-generated content</h2>
          <p>All verdicts and commentary are generated by AI. They may be inaccurate, unfair, or miss context. The AI judges visible behavior in screenshots — it cannot know the full story. Results go through moderation, but we cannot guarantee all output will be appropriate.</p>
        </section>

        <section>
          <h2 className="text-foreground font-bold mb-2">No warranty</h2>
          <p>This service is provided &quot;as is&quot; without warranty of any kind. We don&apos;t guarantee uptime, accuracy, or availability. We may modify or discontinue the service at any time.</p>
        </section>

        <section>
          <h2 className="text-foreground font-bold mb-2">Rate limits</h2>
          <p>Usage is rate-limited to prevent abuse. Excessive or automated use may result in temporary blocks.</p>
        </section>

        <section>
          <h2 className="text-foreground font-bold mb-2">Liability</h2>
          <p>We are not liable for any damages arising from your use of this service, including but not limited to hurt feelings, damaged friendships, or group chat drama escalation.</p>
        </section>

        <section>
          <h2 className="text-foreground font-bold mb-2">Contact</h2>
          <p>Questions? Reach us at <a href="https://ente.com" target="_blank" rel="noopener" className="text-accent hover:underline">ente.com</a>.</p>
        </section>
      </div>

      <a href="/" className="mt-12 text-accent font-[family-name:var(--font-pixel)] text-[10px] hover:underline">BACK TO COURT</a>
    </main>
  );
}
